### PR TITLE
use stable rust

### PR DESCRIPTION
**Pull request by alexander-buerger-met-no**
- use hidefix 0.11.1
- use divan for benches

### CODE REVIEW

**Comment by alexander-buerger-met-no** [comment]
@magnusuMET  I am not sure how to avoid the `make_extents` function in dars/src/lib.rs. This function is copied from the hidefix tests for `Extents`.

**Comment by magnusuMET** [comment]
I don't see an easy way since type inference through the result type is tricky. You might make `stream_xdr` take an `Extents` instead, pushing the trouble of making `Extents` upwards in the stack

**Comment by magnusuMET** [comment]
The memory leak is from `H5MM_xstrdup`, found by running
```shell
env RUSTFLAGS="-Z sanitizer=address" ASAN_SYMBOLIZER_PATH=/usr/bin/llvm-symbolizer-14 cargo test --target x86_64-unknown-linux-gnu -p dars --test coads -- --nocapture coads_subset
```

**Comment by magnusuMET** [comment]
We run the address sanitizer in the `hdf5` crate which does not reveal any leaks. The backtrace isn't very helpful either and I am not sure how to track down the leak

**Comment by gauteh** [comment]
Maybe it is caused by dars, some of the attribute stuff is using hdf
directly.

ons. 14. aug. 2024, 11:01 skrev Magnus Ulimoen ***@***.***>:

**Comment by magnusuMET** [comment]
Reading `data/dmrpp/unused/ntypes.h5` gives the memory leak

**Comment by gauteh** [comment]
> Reading `data/dmrpp/unused/ntypes.h5` gives the memory leak, in specific the `compound_type_4` dataset

Those files were found in the hyrax test suite. They also appear to be less unused than the path suggests.

**Comment by magnusuMET** [comment]
I removed that troublesome file. If someone wants to hunt down that leak we can always add it back in.

Clippy was also really strict for package metadata, if we are planning on releasing the crates on crates.io we could blacklist the warnings again.

**Comment by gauteh** [comment]
Great! Thanks a lot both!

**Pull request merged**
